[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-cors = "0.7"
serde = { version = "1", features=["derive"] }
serde_json = "1"
jsonwebtoken = "9"
sqlx = { version = "0.7", features=["postgres", "runtime-tokio", "tls-none"] }
tokio = { version = "1", features=["macros", "rt-multi-thread"] }
dotenvy = "0.15"
